---
- hosts: all
  tasks:
    - name: installing apache weserver
      yum: name=httpd state=installed
    - name: copying image - index - script -style files                
      copy: src=/root/Desktop/Digitalclock/img dest=/var/www/html/img
    - name: copying index.html
      copy: src=/root/Desktop/Digitalclock/index.html dest=/var/www/html/index.html
    - name: copying script.js file
      copy: src=/root/Desktop/Digitalclock/script.js dest=/var/www/html/script.js
    - name: copying css file
      copy: src=/root/Desktop/Digitalclock/style.css dest=/var/www/html/style.css
    - name: starting the apache web-server service
      service: name=httpd state=started

